"""Asset class registry — static definitions for watchlist asset types."""

ASSET_CLASSES = {
    "stock": {
        "slug": "stock",
        "label": "Stocks",
        "icon": "trending-up",
        "columns": [
            {"key": "name", "label": "Name", "width": "200px", "source": "item", "align": "left", "format": None},
            {"key": "symbol", "label": "Symbol", "width": "90px", "source": "item", "align": "left", "format": None},
            {"key": "industry", "label": "Industry", "width": "120px", "source": "cache", "align": "left", "format": None},
            {"key": "sector", "label": "Sector", "width": "120px", "source": "cache", "align": "left", "format": None},
            {"key": "current_price", "label": "Price", "width": "80px", "source": "cache", "align": "right", "format": "price"},
            {"key": "day_change_pct", "label": "Day Chg%", "width": "80px", "source": "cache", "align": "right", "format": "change_pct"},
            {"key": "pe_ratio", "label": "PE", "width": "60px", "source": "cache", "align": "right", "format": "decimal"},
            {"key": "pb_ratio", "label": "PB", "width": "60px", "source": "cache", "align": "right", "format": "decimal"},
            {"key": "market_cap", "label": "Mkt Cap", "width": "90px", "source": "cache", "align": "right", "format": "compact"},
            {"key": "roe", "label": "ROE", "width": "60px", "source": "cache", "align": "right", "format": "pct_mult"},
            {"key": "eps", "label": "EPS", "width": "60px", "source": "cache", "align": "right", "format": "decimal"},
            {"key": "dividend_yield", "label": "Div Yield", "width": "70px", "source": "cache", "align": "right", "format": "pct_mult"},
            {"key": "fifty_two_week_range", "label": "52W Range", "width": "120px", "source": "cache", "align": "left", "format": "range"},
            {"key": "sparkline", "label": "", "width": "90px", "source": "special", "align": "left", "format": "sparkline"},
            {"key": "stage", "label": "Status", "width": "100px", "source": "special", "align": "left", "format": "stage"},
        ],
        "default_columns": [
            "name", "symbol", "current_price", "day_change_pct", "pe_ratio", "pb_ratio",
            "market_cap", "roe", "dividend_yield", "fifty_two_week_range", "sparkline", "stage",
        ],
    },
    "mutual_fund": {
        "slug": "mutual_fund",
        "label": "Mutual Funds",
        "icon": "bar-chart-2",
        "columns": [
            {"key": "name", "label": "Name", "width": "250px", "source": "item", "align": "left", "format": None},
            {"key": "symbol", "label": "Code", "width": "90px", "source": "item", "align": "left", "format": None},
            {"key": "nav", "label": "NAV", "width": "80px", "source": "cache", "align": "right", "format": "price"},
            {"key": "day_change_pct", "label": "Day Chg", "width": "80px", "source": "cache", "align": "right", "format": "change_pct"},
            {"key": "return_1y", "label": "1Y Ret", "width": "70px", "source": "cache", "align": "right", "format": "change_pct"},
            {"key": "return_3y", "label": "3Y Ret", "width": "70px", "source": "cache", "align": "right", "format": "change_pct"},
            {"key": "return_5y", "label": "5Y Ret", "width": "70px", "source": "cache", "align": "right", "format": "change_pct"},
            {"key": "expense_ratio", "label": "Exp Ratio", "width": "80px", "source": "cache", "align": "right", "format": "decimal"},
            {"key": "aum", "label": "AUM", "width": "90px", "source": "cache", "align": "right", "format": "compact"},
            {"key": "category", "label": "Category", "width": "120px", "source": "cache", "align": "left", "format": None},
            {"key": "sparkline", "label": "", "width": "90px", "source": "special", "align": "left", "format": "sparkline"},
            {"key": "stage", "label": "Status", "width": "100px", "source": "special", "align": "left", "format": "stage"},
        ],
        "default_columns": [
            "name", "nav", "day_change_pct", "return_1y", "return_3y", "return_5y",
            "expense_ratio", "category", "sparkline", "stage",
        ],
    },
    "etf": {
        "slug": "etf",
        "label": "ETFs",
        "icon": "layers",
        "columns": [
            {"key": "name", "label": "Name", "width": "220px", "source": "item", "align": "left", "format": None},
            {"key": "symbol", "label": "Symbol", "width": "90px", "source": "item", "align": "left", "format": None},
            {"key": "current_price", "label": "Price", "width": "80px", "source": "cache", "align": "right", "format": "price"},
            {"key": "day_change_pct", "label": "Day Chg%", "width": "80px", "source": "cache", "align": "right", "format": "change_pct"},
            {"key": "nav", "label": "NAV", "width": "80px", "source": "cache", "align": "right", "format": "price"},
            {"key": "expense_ratio", "label": "Exp Ratio", "width": "80px", "source": "cache", "align": "right", "format": "decimal"},
            {"key": "aum", "label": "AUM", "width": "90px", "source": "cache", "align": "right", "format": "compact"},
            {"key": "market_cap", "label": "Mkt Cap", "width": "90px", "source": "cache", "align": "right", "format": "compact"},
            {"key": "holdings_count", "label": "Holdings", "width": "80px", "source": "cache", "align": "right", "format": None},
            {"key": "dividend_yield", "label": "Div Yield", "width": "70px", "source": "cache", "align": "right", "format": "pct_mult"},
            {"key": "fifty_two_week_range", "label": "52W Range", "width": "120px", "source": "cache", "align": "left", "format": "range"},
            {"key": "sparkline", "label": "", "width": "90px", "source": "special", "align": "left", "format": "sparkline"},
            {"key": "stage", "label": "Status", "width": "100px", "source": "special", "align": "left", "format": "stage"},
        ],
        "default_columns": [
            "name", "symbol", "current_price", "day_change_pct", "expense_ratio",
            "aum", "holdings_count", "sparkline", "stage",
        ],
    },
    "precious_metal": {
        "slug": "precious_metal",
        "label": "Precious Metals",
        "icon": "award",
        "columns": [
            {"key": "name", "label": "Name", "width": "200px", "source": "item", "align": "left", "format": None},
            {"key": "symbol", "label": "Symbol", "width": "90px", "source": "item", "align": "left", "format": None},
            {"key": "current_price", "label": "Spot Price", "width": "100px", "source": "cache", "align": "right", "format": "price"},
            {"key": "day_change", "label": "Day Chg", "width": "80px", "source": "cache", "align": "right", "format": "price"},
            {"key": "day_change_pct", "label": "Day Chg%", "width": "80px", "source": "cache", "align": "right", "format": "change_pct"},
            {"key": "fifty_two_week_range", "label": "52W Range", "width": "140px", "source": "cache", "align": "left", "format": "range"},
            {"key": "previous_close", "label": "Prev Close", "width": "90px", "source": "cache", "align": "right", "format": "price"},
            {"key": "sparkline", "label": "", "width": "90px", "source": "special", "align": "left", "format": "sparkline"},
            {"key": "stage", "label": "Status", "width": "100px", "source": "special", "align": "left", "format": "stage"},
        ],
        "default_columns": [
            "name", "symbol", "current_price", "day_change", "day_change_pct",
            "fifty_two_week_range", "sparkline", "stage",
        ],
    },
    "bond": {
        "slug": "bond",
        "label": "Bonds",
        "icon": "shield",
        "columns": [
            {"key": "name", "label": "Name", "width": "220px", "source": "item", "align": "left", "format": None},
            {"key": "symbol", "label": "Symbol", "width": "100px", "source": "item", "align": "left", "format": None},
            {"key": "current_price", "label": "Price", "width": "80px", "source": "cache", "align": "right", "format": "price"},
            {"key": "bond_yield", "label": "Yield", "width": "70px", "source": "cache", "align": "right", "format": "decimal"},
            {"key": "day_change", "label": "Day Chg", "width": "80px", "source": "cache", "align": "right", "format": "price"},
            {"key": "day_change_pct", "label": "Day Chg%", "width": "80px", "source": "cache", "align": "right", "format": "change_pct"},
            {"key": "previous_close", "label": "Prev Close", "width": "90px", "source": "cache", "align": "right", "format": "price"},
            {"key": "fifty_two_week_range", "label": "52W Range", "width": "120px", "source": "cache", "align": "left", "format": "range"},
            {"key": "sparkline", "label": "", "width": "90px", "source": "special", "align": "left", "format": "sparkline"},
            {"key": "stage", "label": "Status", "width": "100px", "source": "special", "align": "left", "format": "stage"},
        ],
        "default_columns": [
            "name", "symbol", "current_price", "bond_yield", "day_change_pct",
            "fifty_two_week_range", "sparkline", "stage",
        ],
    },
    "crypto": {
        "slug": "crypto",
        "label": "Crypto",
        "icon": "globe",
        "columns": [
            {"key": "name", "label": "Name", "width": "200px", "source": "item", "align": "left", "format": None},
            {"key": "symbol", "label": "Symbol", "width": "100px", "source": "item", "align": "left", "format": None},
            {"key": "current_price", "label": "Price", "width": "100px", "source": "cache", "align": "right", "format": "price"},
            {"key": "day_change_pct", "label": "Day Chg%", "width": "80px", "source": "cache", "align": "right", "format": "change_pct"},
            {"key": "market_cap", "label": "Mkt Cap", "width": "100px", "source": "cache", "align": "right", "format": "compact"},
            {"key": "volume_24h", "label": "Vol 24h", "width": "100px", "source": "cache", "align": "right", "format": "compact"},
            {"key": "circulating_supply", "label": "Circ Supply", "width": "110px", "source": "cache", "align": "right", "format": "compact"},
            {"key": "fifty_two_week_range", "label": "52W Range", "width": "140px", "source": "cache", "align": "left", "format": "range"},
            {"key": "sparkline", "label": "", "width": "90px", "source": "special", "align": "left", "format": "sparkline"},
            {"key": "stage", "label": "Status", "width": "100px", "source": "special", "align": "left", "format": "stage"},
        ],
        "default_columns": [
            "name", "symbol", "current_price", "day_change_pct", "market_cap",
            "volume_24h", "circulating_supply", "sparkline", "stage",
        ],
    },
}


# Common precious metals symbols for search
PRECIOUS_METALS_LIST = [
    {"symbol": "GC=F", "name": "Gold Futures", "exchange": "COMEX"},
    {"symbol": "SI=F", "name": "Silver Futures", "exchange": "COMEX"},
    {"symbol": "PL=F", "name": "Platinum Futures", "exchange": "NYMEX"},
    {"symbol": "PA=F", "name": "Palladium Futures", "exchange": "NYMEX"},
    {"symbol": "HG=F", "name": "Copper Futures", "exchange": "COMEX"},
    {"symbol": "GLD", "name": "SPDR Gold Shares ETF", "exchange": "NYSE"},
    {"symbol": "SLV", "name": "iShares Silver Trust ETF", "exchange": "NYSE"},
    {"symbol": "PPLT", "name": "abrdn Platinum Shares ETF", "exchange": "NYSE"},
]

# Common bond symbols for search
BOND_INSTRUMENTS_LIST = [
    {"symbol": "^TNX", "name": "10-Year Treasury Yield", "exchange": "INDEX"},
    {"symbol": "^TYX", "name": "30-Year Treasury Yield", "exchange": "INDEX"},
    {"symbol": "^FVX", "name": "5-Year Treasury Yield", "exchange": "INDEX"},
    {"symbol": "^IRX", "name": "13-Week Treasury Bill", "exchange": "INDEX"},
    {"symbol": "TLT", "name": "iShares 20+ Year Treasury Bond ETF", "exchange": "NASDAQ"},
    {"symbol": "IEF", "name": "iShares 7-10 Year Treasury Bond ETF", "exchange": "NASDAQ"},
    {"symbol": "SHY", "name": "iShares 1-3 Year Treasury Bond ETF", "exchange": "NASDAQ"},
    {"symbol": "BND", "name": "Vanguard Total Bond Market ETF", "exchange": "NASDAQ"},
    {"symbol": "AGG", "name": "iShares Core U.S. Aggregate Bond ETF", "exchange": "NYSE"},
    {"symbol": "LQD", "name": "iShares iBoxx $ Investment Grade Corporate Bond ETF", "exchange": "NYSE"},
    {"symbol": "HYG", "name": "iShares iBoxx $ High Yield Corporate Bond ETF", "exchange": "NYSE"},
    {"symbol": "BNDX", "name": "Vanguard Total International Bond ETF", "exchange": "NASDAQ"},
]
